//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckIn
    {
        public string Masv { get; set; }
        public System.DateTime ThoiGian { get; set; }
    
        public virtual SINHVIEN SINHVIEN { get; set; }
    }
}
