//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADONDIENNUOC
    {
        public string Mahdn { get; set; }
        public Nullable<int> HDThang { get; set; }
        public string MaNV { get; set; }
        public string Sophong { get; set; }
        public Nullable<System.DateTime> Ngaylap { get; set; }
        public Nullable<decimal> Tongtien { get; set; }
        public Nullable<int> Sokidien { get; set; }
        public Nullable<int> Sokhoinuoc { get; set; }
        public Nullable<decimal> Dongiadien { get; set; }
        public Nullable<decimal> Dongianuoc { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual PHONG PHONG { get; set; }
    }
}
