//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOPDONG
    {
        public string Mahd { get; set; }
        public string Masv { get; set; }
        public string MaNV { get; set; }
        public string Sophong { get; set; }
        public Nullable<System.DateTime> Ngaybatdau { get; set; }
        public Nullable<System.DateTime> Ngayketthuc { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual PHONG PHONG { get; set; }
        public virtual SINHVIEN SINHVIEN { get; set; }
    }
}
