//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIKTX
    {
        public string Mabienlai { get; set; }
        public string Masv { get; set; }
        public string Sophong { get; set; }
        public Nullable<decimal> Sotien { get; set; }
        public Nullable<int> Sothang { get; set; }
        public Nullable<short> Namhoc { get; set; }
        public Nullable<System.DateTime> Ngaythu { get; set; }
    
        public virtual PHONG PHONG { get; set; }
        public virtual SINHVIEN SINHVIEN { get; set; }
    }
}
