//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINHVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SINHVIEN()
        {
            this.HOPDONGs = new HashSet<HOPDONG>();
            this.PHIKTXes = new HashSet<PHIKTX>();
            this.CheckIns = new HashSet<CheckIn>();
        }
    
        public string Masv { get; set; }
        public Nullable<System.DateTime> Ngaysinh { get; set; }
        public string Email { get; set; }
        public string Hoten { get; set; }
        public Nullable<int> Khoa { get; set; }
        public string Gioitinh { get; set; }
        public string Cmnd { get; set; }
        public Nullable<System.DateTime> Ngaycap { get; set; }
        public string Noicap { get; set; }
        public string Dantoc { get; set; }
        public string Tongiao { get; set; }
        public string Sdt { get; set; }
        public string Diachithuongtru { get; set; }
        public string Mahb { get; set; }
        public string MaDTUT { get; set; }
        public string LinkImage { get; set; }
    
        public virtual DOITUONGUUTIEN DOITUONGUUTIEN { get; set; }
        public virtual HOCBONG HOCBONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOPDONG> HOPDONGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIKTX> PHIKTXes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckIn> CheckIns { get; set; }
    }
}
